apiVersion: "x4.sap.com/v1"
kind: X4Tenant
metadata:
  name: stepstone-tenant-01
spec:
  tenant: tenant01
  role: OS001
  application: stepstone
  subdomain: test-01
  configuration:
    http://sap.com/x4/admin:
      debugLog: ""
