apiVersion: "x4.sap.com/v1"
kind: X4Tenant
metadata:
  name: x4-bc-dev-tenant-01
spec:
  tenant: tenant01
  role: OS001
  application: cbc-xman-int
  subdomain: x4demo1
  configuration:
    http://sap.com/x4/admin:
      debugLog: ""
