apiVersion: v1
data:
  password: cGFzc3dvcmQ=
  username: dXNlcm5hbWU=
kind: Secret
metadata:
  labels:
    app: osba-open-service-broker-azure
    chart: open-service-broker-azure-1.8.4-patch
    heritage: Helm
    release: osba
  name: osba-open-service-broker-azure-auth
  namespace: osba
type: Opaque
