# {{- if (.Values.serviceCatalog.enabled)}}
apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceBinding
metadata:
  name: x4man-redis-service-binding
spec:
  instanceRef:
    name: x4man-redis-service-instance
  secretName: x4man-redis-secret
# {{- end }}
