# {{- if (.Values.serviceCatalog.enabled)}}
apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceInstance
metadata:
  name: x4man-redis-service-instance
spec:
  clusterServiceClassExternalName: azure-rediscache
  clusterServicePlanExternalName: standard-cssc
# {{- end }}
