apiVersion: "x4.sap.com/v1"
kind: X4ApplicationVersion
metadata:
  name: x4-bc-dev-2.0.3
spec:
  application: x4-bc-dev
  version: 2.0.3
  worker:
    image: x4:042303
  content:
    image: x4:042303
  env:
    - name: VCAP_SERVICES
      valueFrom:
        secretKeyRef:
          name: x4-bc-dev-vcap
          key: content.json
    - name: ENABLE_SAP_INTERNAL_CAPABILITIES
      value: "true"
  # supportTickets:
  #   - debug01
  # approuter:
  #   image: docker.wdf.sap.corp:50000/com.sap.html5.apps/approuter-6.7:6.7.0
