apiVersion: v1
kind: Secret
metadata:
  name: {{secretName}}
  ownerReferences:
    {{#ownerReferences}}
    - apiVersion: {{apiVersion}}
      blockOwnerDeletion: true
      kind: {{kind}}
      name: {{name}}
      uid: {{uid}}
    {{/ownerReferences}}
type: Opaque
data:
  host: {{host}}
  port: {{port}}
  password: {{password}}
  