kind: Service
apiVersion: v1
metadata:
  labels:
    app: {{name}}
  name: {{serviceName}}
  ownerReferences:
    {{#ownerReferences}}
    - apiVersion: {{apiVersion}}
      blockOwnerDeletion: true
      kind: {{kind}}
      name: {{name}}
      uid: {{uid}}
    {{/ownerReferences}}
spec:
  ports:
  - name: tcp-redis-port
    protocol: TCP
    port: 6379
    targetPort: tcp-redis-port
  selector:
    app: {{name}}