kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: {{name}}
  ownerReferences:
    {{#ownerReferences}}
    - apiVersion: {{apiVersion}}
      blockOwnerDeletion: true
      kind: {{kind}}
      name: {{name}}
      uid: {{uid}}
    {{/ownerReferences}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{name}}
  template:
    metadata:
      labels:
        app: {{name}}
    spec:
      containers:
      - name: redis-container
        image: {{image}}
        imagePullPolicy: IfNotPresent
        ports:
        - name: tcp-redis-port
          containerPort: 6379
          protocol: TCP
        volumeMounts:
        - name: {{name}}-data
          mountPath: "/data"
      restartPolicy: Always
      imagePullSecrets:
      {{#imagePullSecrets}}
        - name: {{.}}
      {{/imagePullSecrets}}
      {{^imagePullSecrets}}
        []
      {{/imagePullSecrets}}      
  volumeClaimTemplates:
  - metadata:
      name: {{name}}-data
      annotations:
        volume.alpha.kubernetes.io/storage-class: anything
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: "10Gi"