apiVersion: metacontroller.k8s.io/v1alpha1
kind: DecoratorController
metadata:
  name: appver.x4.sap.com
spec:
  resources:
    - apiVersion: x4.sap.com/v1
      resource: x4appvers
  resyncPeriodSeconds: 30
  hooks:
    sync:
      webhook:
        url: http://xman-app-svc.xman-system.svc/api/hooks/x4appver/sync
        timeout: 120s
    finalize:
      webhook:
        url: http://xman-app-svc.xman-system.svc/api/hooks/x4appver/finalize
        timeout: 120s
