apiVersion: v1
kind: ServiceAccount
metadata:
  name: xman-operator
  namespace: xman-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: xman-operator
subjects:
  - kind: ServiceAccount
    name: xman-operator
    namespace: xman-system
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
