apiVersion: metacontroller.k8s.io/v1alpha1
kind: DecoratorController
metadata:
  name: tenant.x4.sap.com
spec:
  resources:
    - apiVersion: x4.sap.com/v1
      resource: x4tenants
  resyncPeriodSeconds: 30
  hooks:
    sync:
      webhook:
        url: http://xman-app-svc.xman-system.svc/api/hooks/x4tenant/sync
        timeout: 120s
    finalize:
      webhook:
        url: http://xman-app-svc.xman-system.svc/api/hooks/x4tenant/finalize
        timeout: 120s
