{{- if .Values.istio.host }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: xman-vsvc
spec:
  hosts:
    - "{{.Values.istio.host}}"
  gateways:
    - xman-gateway
  http:
    - match:
      - uri:
          prefix: /ide/
      name: ide
      rewrite:
        uri: /
      route:
      - destination:
          host: xman-app-svc
          port:
            number: 81
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: xman-app-svc
            port:
              number: 80
{{- end }}