{{- if and (.Values.xman_pg) (not .Values.serviceCatalog.enabled) }}
{{- if and (.Values.xman_pg.db_user) (.Values.xman_pg.db_password) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: xman-pg-secret
type: Opaque
data:
  database: {{ "postgres" | b64enc }}
  host: {{ "xman-pg-service" | b64enc }}
  username: {{ .Values.xman_pg.db_user | b64enc }}
  password: {{ .Values.xman_pg.db_password | b64enc }}
  sslRequired: {{ "false" | b64enc }}
  port: {{ "5432" | b64enc }}
{{- end }}
{{- end }}