apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argo-workflow
  namespace: xman-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: x4.sap.com:argo-workflow
subjects:
  - kind: ServiceAccount
    name: argo-workflow