apiVersion: v1
kind: Secret
metadata:
  name: auditlogservice
type: Opaque
data:
  content.json: "eyJhdWRpdGxvZyI6W3sibmFtZSI6ImF1ZGl0bG9nIiwiY3JlZGVudGlhbHMiOnsicGFzc3dvcmQiOiIzY2Y2YWVmN2U3ZDFiN2IzIiwidXNlciI6IjgxYjEwYWU3OTViYjMzNTIiLCJ1cmwiOiJodHRwczovL2FwaS5hdWRpdGxvZy5jZi5ldTEwLmhhbmEub25kZW1hbmQuY29tOjgwODEifX1dfQ=="
