apiVersion: v1
kind: Namespace
metadata:
  name: istio-system
---
apiVersion: v1
kind: Namespace
metadata:
  name: argo
---
apiVersion: v1
kind: Namespace
metadata:
  name: metacontroller
---
apiVersion: v1
kind: Namespace
metadata:
  name: xman-system
---
apiVersion: v1
kind: Namespace
metadata:
  name: x4-job-system
