apiVersion: "x4.sap.com/v1"
kind: X4ApplicationVersion
metadata:
  name: x4-bc-dev-2.0.0
spec:
  application: x4-bc-dev
  version: 2.0.0
  worker:
    image: docker.wdf.sap.corp:50000/com.sap.x4-bc-dev-xman-int:20200412
  content:
    image: docker.wdf.sap.corp:50000/com.sap.x4-bc-dev-xman-int:20200412
  env:
    - name: VCAP_SERVICES
      valueFrom:
        secretKeyRef:
          name: x4-bc-dev-vcap
          key: content.json
  # supportTickets:
  #   - debug01
  approuter:
    image: docker.wdf.sap.corp:50000/com.sap.html5.apps/approuter-6.7:6.7.0
