apiVersion: "x4.sap.com/v1"
kind: X4Application
metadata:
  name: x4-bc-xman
spec:
  # baf application artifacts
  jobmanager:
    from: component
    value: jobmanager01
  lockmanager:
    from: component
    value: lockmanager01
  # saasregistry:
  #   serviceInstance: saasregservice
  database:
    from: component
    value: bafdb
  # uaa:
  #   from: secret
  #   value: x4-bc-dev-vcap
  # auditlog:
  #   from: secret
  #   value: auditlogservice
  # destination:
  #   serviceInstance: destinationservice
  # transportation:
  #   serviceInstance: transportationservice
  # certificateservice:
  #   serviceInstance: certificateservice
  # ...
  # baf appliction components
  components:
    - name: bafdb
      type: postgres
      image: postgres:10
    - name: lockmanager01
      type: lockmanager
      image: big.docker.repositories.sap.ondemand.com/com.sap.x4-lock-manager-master/x4-lock-manager:1.1.7
      database:
        from: service
        value: redis
    - name: jobmanager01
      type: jobmanager
      image: big.docker.repositories.sap.ondemand.com/com.sap.x4-job-manager-master/x4-job-manager:2.0.1
      database:
        from: component
        value: bafdb
  serviceInstances:
    - name: redis
      serviceName: azure-rediscache
      servicePlan: standard-cssc
  env:
    # - name: "VCAP_SERVICES"
    #   valueFrom:
    #     secretKeyRef:
    #       name: x4-bc-dev-vcap
    #       key: content.json
    - name: ENABLE_SAP_INTERNAL_CAPABILITIES
      value: "true"
  gateway:
    host: x4-bc-xman-master.x4-sample-master.xman.eu.one.cloud.sap
  supportUsers:
    - yu.yu01@sap.com
  imagePullSecrets:
    - regcred
  configuration: {}
