apiVersion: "x4.sap.com/v1"
kind: X4Application
metadata:
  name: x4-bc-dev
spec:
  # baf application artifacts
  jobmanager:
    from: component
    value: jobmanager01
  lockmanager:
    from: component
    value: lockmanager01
  # saasregistry:
  #   serviceInstance: saasregservice
  database:
    from: component
    value: bafdb
  # uaa:
  #   from: secret
  #   value: x4-bc-dev-vcap
  # auditlog:
  #   from: secret
  #   value: auditlogservice
  # destination:
  #   serviceInstance: destinationservice
  # transportation:
  #   serviceInstance: transportationservice
  # certificateservice:
  #   serviceInstance: certificateservice
  # ...
  # baf appliction components
  components:
    - name: lockmanager01
      type: lockmanager
      image: docker.wdf.sap.corp:50000/com.sap.x4-lock-manager-master/x4-lock-manager:1.1.7
      database:
        from: service
        value: redis
    - name: jobmanager01
      type: jobmanager
      image: docker.wdf.sap.corp:50000/com.sap.x4-job-manager-master/x4-job-manager:1.2.0
      database:
        from: service
        value: bafdb
  serviceInstances:
    - name: bafdb
      serviceName: azure-postgresql-9-6
      servicePlan: basic
      parameters:
        location: eastus
        resourceGroup: demo
        extensions:
          - uuid-ossp
          - postgis
        firewallRules:
          - startIPAddress: "0.0.0.0"
            endIPAddress: "255.255.255.255"
            name: "AllowAll"
    - name: redis
      serviceName: azure-rediscache
      servicePlan: standard-cssc
  gateway:
    host: x4-bc-xman.x4-sample-dev.xman.eu.one.cloud.sap
  supportUsers:
    - yu.yu01@sap.com
  imagePullSecrets:
    - regcred
  env:
    - name: "VCAP_SERVICES"
      valueFrom:
        secretKeyRef:
          name: x4demo-vcap-secret
          key: content.json
  configuration: {}
