---
apiVersion: "x4.sap.com/v1"
kind: X4ApplicationVersion
metadata:
  name: x4-bc-1.0.0
  namespace: x4-bc-xman-master
spec:
  application: x4-bc
  version: 1.0.0
  worker:
    image: big.docker.repositories.sap.ondemand.com/com.sap.x4-bc-dev/x4-bc:2.0.0-20200427122154_3dc45ece90dd9f9f733ef409ceb1369b2e5f46e0
  content:
    image: big.docker.repositories.sap.ondemand.com/com.sap.x4-bc-dev/x4-bc:2.0.0-20200427122154_3dc45ece90dd9f9f733ef409ceb1369b2e5f46e0
  # env:
  #   - name: "VCAP_SERVICES"
  #     valueFrom:
  #       secretKeyRef:
  #         name: x4demo-vcap-secret
  #         key: content.json
  #   - name: ENABLE_SAP_INTERNAL_CAPABILITIES
  #     value: "true"
  # supportTickets:
  #   - debug01
  # approuter:
  #   image: docker.wdf.sap.corp:50000/com.sap.html5.apps/approuter-6.7:6.7.0
