# Case2: provision postgres for jobmanager, hana for BAF system, postgres for BAF repository, redis for lockmanager, uaa service for login via service catalog.
apiVersion: "x4.sap.com/v1"
kind: X4Application
metadata:
  name: x4-app
spec:
  components:
    - name: lockmanager01
      type: lockmanager
      image: docker.wdf.sap.corp:50000/com.sap.x4/x4-lock-manager:1.1.5
      database:
        serviceInstance: lockmanagerredis01
    - name: jobmanager01
      type: jobmanager
      image: docker.wdf.sap.corp:50000/com.sap.x4/x4-job-manager:1.1.0
      database:
        serviceInstance: jobmanagerdb01
  serviceInstances:
    - name: lockmanagerredis01
      serviceName: azure-redis
      servicePlan: basic
      parameters: {}
    - name: jobmanagerdb01
      serviceName: azure-postgresql-9-6
      servicePlan: basic
      parameters:
        location: eastus
        resourceGroup: demo
        extensions:
          - uuid-ossp
          - postgis
        firewallRules:
          - startIPAddress: "0.0.0.0"
            endIPAddress: "255.255.255.255"
            name: "AllowAll"
    - name: repodb
      serviceName: azure-postgresql-9-6
      servicePlan: basic
      parameters:
        location: eastus
        resourceGroup: demo
        extensions:
          - uuid-ossp
          - postgis
        firewallRules:
          - startIPAddress: "0.0.0.0"
            endIPAddress: "255.255.255.255"
            name: "AllowAll"
    - name: bafdb
      serviceName: azure-hana
      servicePlan: basic
      parameters: {}
    - name: uaaservice01
      serviceName: xsuaa
      servicePlan: basic
      parameters: {}
  gateway:
    hosts:
      - x4-bc.local
    tls:
      credentialName: bookinfo-secret
  jobmanager:
    component: jobmanager01
  lockmanager:
    component: lockmanager01
  approuter:
    image: ""
    env:
      -
  uaa:
      serviceInstance: uaaservice
  database:
    system:
      serviceInstance: bafdb
    repository:
      serviceInstance: repodb
  supportUsers:
    - SAP_SUPP001
    - SAP_SUPP002
    - SAP_SUPP003
  vcapSecret: ""
  imagePullSecrets:
    - cred
  env:
    -
  # configuration which will be imported into the system schema of the application
  configuration: {}