---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: argo-workflow
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argo-workflow
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: x4.sap.com:argo-workflow
subjects:
  - kind: ServiceAccount
    name: argo-workflow
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: x4job
description: This priority class should be used for x4job service pods only.
value: 1000000
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: x4jobquota
spec:
  hard:
    pods: "5"
  scopeSelector:
    matchExpressions:
      - operator: In
        scopeName: PriorityClass
        values:
          - x4job
---
apiVersion: v1
kind: Secret
metadata:
  name: x4-bc-dev-vcap
type: Opaque
data:
  content.json: ewogICJvYmplY3RzdG9yZSI6IFsKICAgIHsKICAgICAgImJpbmRpbmdfbmFtZSI6IG51bGwsCiAgICAgICJjcmVkZW50aWFscyI6IHsKICAgICAgICAiYXV0aF91cmwiOiAiaHR0cHM6Ly9pZGVudGl0eS0zLmV1LWRlLTIuY2xvdWQuc2FwOjQ0MyIsCiAgICAgICAgImNvbnRhaW5lcl9uYW1lIjogImNvbnRlbnQtbWFuYWdlbWVudCIsCiAgICAgICAgInBhc3N3b3JkIjogIjhhdUQ5bUZYelQ2azlEam4iLAogICAgICAgICJwcm9qZWN0IjogIng0LXRlc3QiLAogICAgICAgICJwcm9qZWN0X2RvbWFpbiI6ICJtb25zb29uMyIsCiAgICAgICAgInVzZXJfZG9tYWluIjogIm1vbnNvb24zIiwKICAgICAgICAidXNlcm5hbWUiOiAiVE0zX0kwMzk4MThfMDIiCiAgICAgIH0sCiAgICAgICJsYWJlbCI6ICJvYmplY3RzdG9yZSIsCiAgICAgICJwbGFuIjogInN3aWZ0LXN0YW5kYXJkIiwKICAgICAgInByb3ZpZGVyIjogIm9wZW5zdGFjayIsCiAgICAgICJ0YWdzIjogWwogICAgICAgICJvYmplY3RTdG9yZSIKICAgICAgXQogICAgfQogIF0sCiAgImF1ZGl0bG9nIjogWwogICAgewogICAgICAiYmluZGluZ19uYW1lIjogbnVsbCwKICAgICAgImNyZWRlbnRpYWxzIjogewogICAgICAgICJwYXNzd29yZCI6ICI1ZmJmNWI5YmI4ZDVhMTlkIiwKICAgICAgICAidXJsIjogImh0dHBzOi8vYXBpLmF1ZGl0bG9nLmNmLmV1MTAuaGFuYS5vbmRlbWFuZC5jb206ODA4MSIsCiAgICAgICAgInVzZXIiOiAiYmZhOWU5NzYzMGQzN2IwMiIKICAgICAgfSwKICAgICAgImluc3RhbmNlX25hbWUiOiAiYmNhdWRpdGxvZyIsCiAgICAgICJsYWJlbCI6ICJhdWRpdGxvZyIsCiAgICAgICJuYW1lIjogImF1ZGl0bG9nIiwKICAgICAgInBsYW4iOiAic3RhbmRhcmQiLAogICAgICAicHJvdmlkZXIiOiBudWxsLAogICAgICAidGFncyI6IFsKICAgICAgICAiYXVkaXRsb2ciCiAgICAgIF0KICAgIH0KICBdLAogICJ1YWEiOiBbCiAgICB7CiAgICAgICJsYWJlbCI6ICJ4c3VhYSIsCiAgICAgICJwcm92aWRlciI6IG51bGwsCiAgICAgICJwbGFuIjogImJyb2tlciIsCiAgICAgICJuYW1lIjogIng0dWFhIiwKICAgICAgInRhZ3MiOiBbCiAgICAgICAgInhzdWFhIgogICAgICBdLAogICAgICAiaW5zdGFuY2VfbmFtZSI6ICJ4NHVhYSIsCiAgICAgICJiaW5kaW5nX25hbWUiOiBudWxsLAogICAgICAiY3JlZGVudGlhbHMiOiB7CiAgICAgICAgImFwaXVybCI6ICJodHRwczovL2FwaS5hdXRoZW50aWNhdGlvbi5ldTEwLmhhbmEub25kZW1hbmQuY29tIiwKICAgICAgICAiY2xpZW50aWQiOiAic2IteG1hbi1sb2NhbCFiMjE1NzciLAogICAgICAgICJjbGllbnRzZWNyZXQiOiAiRFh1amxBT2N1amE4SllaeWg0dzY0TkduTDNnPSIsCiAgICAgICAgImlkZW50aXR5em9uZSI6ICJjYmN4NCIsCiAgICAgICAgImlkZW50aXR5em9uZWlkIjogIjlkYTEzYWE4LWM5MzAtNDM3My1hOWE1LTU0N2Q3NzFlNGI5MiIsCiAgICAgICAgInNidXJsIjogImh0dHBzOi8vaW50ZXJuYWwteHN1YWEuYXV0aGVudGljYXRpb24uZXUxMC5oYW5hLm9uZGVtYW5kLmNvbSIsCiAgICAgICAgInRlbmFudGlkIjogIjlkYTEzYWE4LWM5MzAtNDM3My1hOWE1LTU0N2Q3NzFlNGI5MiIsCiAgICAgICAgInRlbmFudG1vZGUiOiAic2hhcmVkIiwKICAgICAgICAidHJ1c3RlZGNsaWVudGlkc3VmZml4IjogInx4bWFuLWxvY2FsIWIyMTU3NyIsCiAgICAgICAgInVhYWRvbWFpbiI6ICJhdXRoZW50aWNhdGlvbi5ldTEwLmhhbmEub25kZW1hbmQuY29tIiwKICAgICAgICAidXJsIjogImh0dHBzOi8vY2JjeDQuYXV0aGVudGljYXRpb24uZXUxMC5oYW5hLm9uZGVtYW5kLmNvbSIsCiAgICAgICAgInZlcmlmaWNhdGlvbmtleSI6ICItLS0tLUJFR0lOIFBVQkxJQyBLRVktLS0tLU1JSUNJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBZzhBTUlJQ0NnS0NBZ0VBd1RobjZPTzlrajBiY2hrT0drcVlCblYxZFEzelUveHRqN0tqN25EZDhueVJNY0VXQ3RWenJ6anpoaWlzUmhscnpsUklFWTgyd1JBWk5HS01udzdjdkN3Tml4Y2ZjREpuanpncjJwSis1L3lEWlVjMElYWHlJV1BaRCtYZEwrMEVvZ0MzZDQrZnF5dmcvQkYvRjB0MmhLSFdyL1VUWEU2enJHaEJLYUwwZDhyS2ZZZDZvbEdXaWdGZCszKzI0Q0tJMTR6V1Z4VUJ0QytQOUZobmdjOURSemtYcWh4T0svRUtuMEh6U2dvdGY1ZHVxNlRtazlEQ05NNHNMVzQrRVJjNnh6cmdiZUVleGFrYWJ2YXgvQXo5V1o0cWh3Z3crZndJaEtJQzdXTHdDRUphUnNXNG03TktrditlSlIyTEtZZXN1UTlTVkFKM0VYVjg2Undkbkg0dUF2N2xRSHNLVVJQVkFRQmxyYW5TcXlRdTBFWHMyTjlPbFdUeGUrRnlOa0l2eVp2b0xyWmwvQ2RsWWM4QUt4Um01cm4yLzg4bmtyWVEwWFpTcm5JQ001RlJXZ1ZGMmhuNUtmWkd3dEJOODUvRDRZY2s2QjNvY01meVg3ZTRVUlVtOWxSUFFGVUpHVFhhWm5FSWdlMFIxNTlIVXdoVE4xSHZ5WHJzNnVUMVpabVcrYzNwNDdkdzErTG1VZi9oSWY4emQrdXZIUWpJZUhFSnF4anFmeUE4eXFBRktSSEtWRnJ3bndkTUhJc1JhcDJFS0JoSE1mZVZmMFAydGg1QzlNZ2dZb0dDdmRJYUlVZ01CWDNUdENkdkdyY1dNTDdobnlTMnprcmxBOFNvS0puUmNSRjJLeFdLczM1NUZocEhwenF5WmZsTzVsOTgrTzh3T3NGakdwTDlkMEVDQXdFQUFRPT0tLS0tLUVORCBQVUJMSUMgS0VZLS0tLS0iLAogICAgICAgICJ4c2FwcG5hbWUiOiAieG1hbi1sb2NhbCFiMjE1NzciCiAgICAgIH0sCiAgICAgICJzeXNsb2dfZHJhaW5fdXJsIjogbnVsbCwKICAgICAgInZvbHVtZV9tb3VudHMiOiBbXQogICAgfQogIF0KfQo=
