apiVersion: "x4.sap.com/v1"
kind: X4ApplicationVersion
metadata:
  name: x4-bc-xman-1.0.0
spec:
  application: x4-bc-xman
  version: 1.0.0
  worker:
    image: big.docker.repositories.sap.ondemand.com/internal-x4-stepstone:xman-test
  content:
    image: big.docker.repositories.sap.ondemand.com/internal-x4-stepstone:xman-test
  # env:
  #   - name: VCAP_SERVICES
  #     valueFrom:
  #       secretKeyRef:
  #         name: x4demo-vcap-secret
  #         key: content.json
  #   - name: ENABLE_SAP_INTERNAL_CAPABILITIES
  #     value: "true"
  # supportTickets:
  #   - ticket0001
  # approuter:
  #   image: build-milestones.docker.repositories.sap.ondemand.com/com.sap.html5.apps/approuter-6.7:6.7.0
